#!/bin/bash

# Enter the path to the text files generated by ocr pipeline
FILES="british-ufo-files/DEFE-31-175/outtxt/"
# Enter the name of the output directory
OUTPUTDIR="shellop/DEFE-31-175_opennlp/"
# Enter the path of the tika config file to invoke the tika jar in command line
TIKACONFIG=$HOME"/tika-config.xml"

mkdir -p $OUTPUTDIR

# Make sure these path variables are available before running the script
# Path to open nlp binary
echo $NER_RES
# Path to tika jar to be invoked from command line
echo $TIKA_APP
# Path to core nlp jar
echo $CORE_NLP_JAR

for f in $( ls $FILES ); do
  # 1) Command to run open nlp ner tagger, uncomment 1 to run OPEN NLP TAGGER
  java -classpath $NER_RES:$TIKA_APP org.apache.tika.cli.TikaCLI --config=$TIKACONFIG -m $FILES$f | grep "^NER" >> $OUTPUTDIR/$f

  # 2) Command to run core nlp ner tagger, uncomment 2 to run CORE NLP TAGGER
  # java -Dner.impl.class=org.apache.tika.parser.ner.corenlp.CoreNLPNERecogniser -classpath $TIKA_APP:$CORE_NLP_JAR org.apache.tika.cli.TikaCLI  --config=$TIKACONFIG -m $FILES$f | grep "^NER" >>$OUTPUTDIR$f
done
